kind: pipeline
type: docker
name: dronetest

steps: 
- name: 71dese1bif/test
  image: adoptopenjdk/maven-openjdk11
  commands:
  - mvn assembly:assembly
  - java -jar target/calc-1.0-SNAPSHOT-jar-with-dependencies.jar &
  - curl localhost:8080/calc/sum/1/1
  settings: 
  auto_tag: true
  auto_tag_suffix: 71dese1bif/
trigger: 
  event: 
  - push
  - tag