kind: pipeline
type: docker
name: dronetest

steps: 
- name: 71dese1bif/test
  image: maven
  commands:
  - mvn assembly:assembly
  - java -jar target/calc-1.0-SNAPSHOT-jar-with-dependencies.jar &
  settings: 
  auto_tag: true
  auto_tag_suffix: 71dese1bif/
  username: 71dese1bif
  password: domsm15963
  repo: 71dese1bif/hft-cc
  tags: latest